### ISSUE TITLE
Cawt test failures

### ISSUE THREAD

**Issue by apnadkarni** [apnadkarni/twapi#10]
CAWT (trunk) test failures with both Tcl/TWAPI 8.6/4.7 and 9.0/5.0a1

8.6/4.7 - 
[RunTests-47.log](https://github.com/apnadkarni/twapi/files/14892737/RunTests-47.log)

9.0/5.0 - 
[runtests-50.log](https://github.com/apnadkarni/twapi/files/14892739/runtests-50.log)

**Comment by apnadkarni** [comment]
Both 4.7 and 5.0 log shows
```
Test Excel-30_SelectRange.tcl failed: Check: Range String (Expected: "A1:C2;B4:C6" Have: "A1:C2;B4:C6")
```

The message is a red herring. In fact the Expected values do match (which is why they are preceded by `Check` and not `Error`. The test itself is reported as failed because the following call

```
    set rangeId [Excel SelectRangeByString $worksheetId $rangeStr true]
```
raises an exception which is reported as a test failure. The reason the exception is raised is the call

```
        set rangeId [$cellsId Range $rangeStr]
```
in `SelectRangeByString`. The `Range` method raises the exception because on US English systems it expects commas as the "union" operator. On European systems, it expects semicolons as above.

The `CreateRangeString` command should perhaps use a locale-specific separator but I could not find a Excel function to retrieve the appropriate separator like there is for decimals and thousands. [This](https://exceljet.net/glossary/list-separator) post explains control panel settings are the source of the separator for the system. `CreateRangeString` could may be use `twapi::get_locale_info` to get that information.

```
% twapi::get_locale_info 0 -slist
-slist ,
```

**Comment by apnadkarni** [comment]
Further issues reported by Paul -

I also see some failing tests, when running the complete test suite of an Office application, ex. tclsh RunTest.tcl Excel
But when I run the failing test outside of the RunTest.tcl script, it works.
This seemed to be a timing problem, so there is an option "--wait" in RunTest.tcl to specify the milliseconds to wait
till starting the next test.

But the real source of problems seems to be the clipboard on Windows 11, which can hold multiple entries.
An example is test Ppt-03_Add.tcl.
If there is content in the clipboard (like some text), I get the error:
Slides.Paste : Invalid request.  Clipboard is empty or contains data which may not be pasted here.
If clearing the clipboard before running the test, everything works fine.

While experimenting with the clipboard, I noticed a strange behaviour:
package require twapi
twapi::open_clipboard
twapi::empty_clipboard
twapi::write_clipboard 1 "ABCDE"
twapi::close_clipboard

only writes string "ABCD" into the clipboard.
This also happens with twapi 4.7.2.

Paul
Am 05.04.2024 um 06:01 schrieb [apnmbx-public@yahoo.com](mailto:apnmbx-public@yahoo.com):
Downloaded your cawt repo and seeing some crashes in excel (not in tcl). Not always reproducible. Will try to track down later. Also not sure whether my latest changes introduced these.
 
Just FYI
 
/Ashok

**Comment by apnadkarni** [comment]
Paul,

Regarding the clipboard ABCDE issue, it works as designed. Twapi::write_clipboard expects the raw data to be supplied as a binary string. For text that means it needs to include the terminating nul. It must also be encoded in the system encoding. So (ignoring system encoding for ascii),

Twapi::write_clipboard 1 ABCDE\0

In terms of behavior it seems Windows always assumes the last char is a nul without actually checking. So writing ABC will retrieve AB.

With respect to the error Clipboard is empty or contains data which may not be pasted here, lots of people writing macros in VBA have reported that as well with various workarounds including delays. I have to look at it further but I do not think it is a twapi or CAWT issue.

**Comment by PaulObermeier** [comment]
> Both 4.7 and 5.0 log shows
> 
> ```
> Test Excel-30_SelectRange.tcl failed: Check: Range String (Expected: "A1:C2;B4:C6" Have: "A1:C2;B4:C6")
> ```
> 
> The message is a red herring. In fact the Expected values do match (which is why they are preceded by `Check` and not `Error`. The test itself is reported as failed because the following call
> 
> ```
>     set rangeId [Excel SelectRangeByString $worksheetId $rangeStr true]
> ```
> 
> raises an exception which is reported as a test failure. The reason the exception is raised is the call
> 
> ```
>         set rangeId [$cellsId Range $rangeStr]
> ```
> 
> in `SelectRangeByString`. The `Range` method raises the exception because on US English systems it expects commas as the "union" operator. On European systems, it expects semicolons as above.
> 
> The `CreateRangeString` command should perhaps use a locale-specific separator but I could not find a Excel function to retrieve the appropriate separator like there is for decimals and thousands. [This](https://exceljet.net/glossary/list-separator) post explains control panel settings are the source of the separator for the system. `CreateRangeString` could may be use `twapi::get_locale_info` to get that information.
> 
> ```
> % twapi::get_locale_info 0 -slist
> -slist ,
> ```

get_local_info added to Excel::CreateRangeString.

**Comment by apnadkarni** [comment]
I think this issue is resolved. Please re-open if not.
