### ISSUE TITLE
Twapi 5.0b1 warnings when building in 32-bit mode

### ISSUE THREAD

**Issue by PaulObermeier** [apnadkarni/twapi#13]
When building Twapi with Tcl 8.6.15 or 9.0 in 32-bit mode, the following warnings are issued by gcc 7.2.0.
In 64-bit mode no warnings are issued.

win/etw.c: In function 'ObjToPEVENT_TRACE_PROPERTIES':
win/etw.c:505:35: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             etP->LoggerThreadId = (HANDLE) wide;
                                   ^
win/etw.c: In function 'ObjFromEVENT_TRACE_PROPERTIES':
win/etw.c:559:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     objs[18] = ObjFromWideInt((Tcl_WideInt) etP->LoggerThreadId);
                               ^
win/etw.c: In function 'Twapi_TraceEvent':
win/etw.c:755:25: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     event.eth.GuidPtr = (ULONGLONG) &gETWProviderEventClassGuid;
                         ^
win/etw.c:762:32: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
         event.mof[i].DataPtr = (ULONG64) temp;
                                ^
win/etw.c: In function 'TwapiTdhPropertyArraySize':
win/etw.c:996:24: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     pdd.PropertyName = (ULONGLONG)(teiP->EventPropertyInfoArray[ref_index].NameOffset + (char*) teiP);
                        ^
win/etw.c: In function 'TwapiDecodeEVENT_PROPERTY_INFO':
win/etw.c:1519:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     prop_name = (ULONGLONG)(epiP->NameOffset + (char*) teiP);
                 ^
win/etw.c:1536:49: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
                 *propnameObjP = ObjFromWinChars((WCHAR *)(prop_name));
                                                 ^
win/etw.c:1577:39: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                 pdd[0].PropertyName = (ULONGLONG)struct_name;
                                       ^
win/etw.c: In function 'TwapiETWEventRecordCallback':
win/etw.c:1834:62: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             ObjAppendElement(NULL, recObjs[2], ObjFromGUID(&((PEVENT_EXTENDED_ITEM_RELATED_ACTIVITYID)ehdrP->DataPtr)->RelatedActivityId));
                                                              ^
win/etw.c:1838:65: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             ObjAppendElement(NULL, recObjs[2], ObjFromSIDNoFail((SID *)(ehdrP->DataPtr)));
                                                                 ^
win/etw.c:1842:62: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             ObjAppendElement(NULL, recObjs[2], ObjFromULONG(((PEVENT_EXTENDED_ITEM_TS_ID)ehdrP->DataPtr)->SessionId));
                                                              ^
win/etw.c:1846:37: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             objs[0] = ObjFromULONG(((PEVENT_EXTENDED_ITEM_INSTANCE)ehdrP->DataPtr)->InstanceId);
                                     ^
win/etw.c:1847:37: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             objs[1] = ObjFromULONG(((PEVENT_EXTENDED_ITEM_INSTANCE)ehdrP->DataPtr)->ParentInstanceId);
                                     ^
win/etw.c:1848:37: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
             objs[2] = ObjFromGUID(&((PEVENT_EXTENDED_ITEM_INSTANCE)ehdrP->DataPtr)->ParentGuid);

Using Tcl9 the following additional warnings are issued:

win/memlifo.c: In function 'MemLifoAlloc':
win/memlifo.c:166:23: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'MemLifoSize {aka long unsigned int}' [-Wformat=]
             Tcl_Panic("Attempt to allocate %" TCL_SIZE_MODIFIER "u bytes for memlifo", sz);
                       ^~~~~~~~~~~~~~~~~~~~~~~
win/memlifo.c:166:66: note: format string is defined here
             Tcl_Panic("Attempt to allocate %" TCL_SIZE_MODIFIER "u bytes for memlifo", sz);
                                            ~~~~~~~~~~~~~~~~~~~~~~^
                                            %" TCL_SIZE_MODIFIER "lu
win/memlifo.c:242:27: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'MemLifoSize {aka long unsigned int}' [-Wformat=]
                 Tcl_Panic("Attempt to allocate %" TCL_SIZE_MODIFIER "u bytes for memlifo", chunk_sz);
                           ^~~~~~~~~~~~~~~~~~~~~~~
win/memlifo.c:242:70: note: format string is defined here
                 Tcl_Panic("Attempt to allocate %" TCL_SIZE_MODIFIER "u bytes for memlifo", chunk_sz);
                                                ~~~~~~~~~~~~~~~~~~~~~~^
                                                %" TCL_SIZE_MODIFIER "lu
win/memlifo.c:269:27: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'MemLifoSize {aka long unsigned int}' [-Wformat=]
                 Tcl_Panic("Attempt to allocate %" TCL_SIZE_MODIFIER "u bytes for memlifo", chunk_sz);
                           ^~~~~~~~~~~~~~~~~~~~~~~
win/memlifo.c:269:70: note: format string is defined here
                 Tcl_Panic("Attempt to allocate %" TCL_SIZE_MODIFIER "u bytes for memlifo", chunk_sz);
                                                ~~~~~~~~~~~~~~~~~~~~~~^
                                                %" TCL_SIZE_MODIFIER "lu
win/memlifo.c: In function 'MemLifoPushMark':
win/memlifo.c:345:27: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'MemLifoSize {aka long unsigned int}' [-Wformat=]
                 Tcl_Panic("Attempt to allocate %" TCL_SIZE_MODIFIER "u bytes for memlifo", l->lifo_chunk_size);
                           ^~~~~~~~~~~~~~~~~~~~~~~                                          ~~~~~~~~~~~~~~~~~~
win/memlifo.c:345:70: note: format string is defined here
                 Tcl_Panic("Attempt to allocate %" TCL_SIZE_MODIFIER "u bytes for memlifo", l->lifo_chunk_size);
                                                ~~~~~~~~~~~~~~~~~~~~~~^
                                                %" TCL_SIZE_MODIFIER "lu
win/memlifo.c: In function 'MemLifoPushFrame':
win/memlifo.c:437:23: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'MemLifoSize {aka long unsigned int}' [-Wformat=]
             Tcl_Panic("Attempt to allocate %" TCL_SIZE_MODIFIER "u bytes for memlifo", sz);
                       ^~~~~~~~~~~~~~~~~~~~~~~
win/memlifo.c:437:66: note: format string is defined here
             Tcl_Panic("Attempt to allocate %" TCL_SIZE_MODIFIER "u bytes for memlifo", sz);
                                            ~~~~~~~~~~~~~~~~~~~~~~^
                                            %" TCL_SIZE_MODIFIER "lu
win/memlifo.c:492:19: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'MemLifoSize {aka long unsigned int}' [-Wformat=]
         Tcl_Panic("Attempt to allocate %" TCL_SIZE_MODIFIER "u bytes for memlifo", sz);
                   ^~~~~~~~~~~~~~~~~~~~~~~
win/memlifo.c:492:62: note: format string is defined here
         Tcl_Panic("Attempt to allocate %" TCL_SIZE_MODIFIER "u bytes for memlifo", sz);
                                        ~~~~~~~~~~~~~~~~~~~~~~^
                                        %" TCL_SIZE_MODIFIER "lu

**Comment by apnadkarni** [comment]
Fixed all. Thanks.
